name: AncientMetagenomeDir GeoJSON updates

on: 
  push:
    branches:
      - master

jobs:
  live-status-geosjon-update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.GH_ACTIONS_COMMIT_ACTION }}  
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: geojson
          environment-file: assets/analysis/geojson_environment.yml
          auto-activate-base: true
          channels: conda-forge,defaults
      - name: Generate map geojson
        run: |
          python assets/analysis/scripts/create_geojson.py --anthropogenic ancientmetagenome-anthropogenic/samples/ancientmetagenome-anthropogenic_samples.tsv \
          --environmental ancientmetagenome-environmental/samples/ancientmetagenome-environmental_samples.tsv \
          --meta_host ancientmetagenome-hostassociated/samples/ancientmetagenome-hostassociated_samples.tsv \
          --single_host ancientsinglegenome-hostassociated/samples/ancientsinglegenome-hostassociated_samples.tsv \
          --geojson assets/analysis/live/ancientmetagenomedir.geo.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip ci] Update AncientMetagenomeDir geojson"
          push_options: --force 
